sudo:
  false

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

before_install:
  - openssl aes-256-cbc -K $encrypted_253ff25ce075_key -iv $encrypted_253ff25ce075_iv -in .credentials.json.enc -out .credentials.json -d

install:
  - python run.py install
  # Temporary workaround
  - rm jtsbq
  - git clone https://github.com/okfn/jsontableschema-bigquery-py.git tmp
  - mv tmp/jtsbq jtsbq

script:
  - python run.py review
  - python run.py test

after_success:
  - python run.py report
